drop table FILM_GENRE IF EXISTS;

drop table FRIENDS IF EXISTS;

drop table GENRE IF EXISTS;

drop table LIKES IF EXISTS;

drop table FILMS IF EXISTS;

drop table MPA_RATE IF EXISTS;

drop table USERS IF EXISTS;

CREATE TABLE IF NOT EXISTS genre
(
    genre_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name     varchar(40) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS mpa_rate
(
    mpa_rate_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        varchar(8) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS films
(
    film_id     int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title       varchar(150) NOT NULL,
    description varchar(200),
    releaseDate date         NOT NULL,
    duration    int          NOT NULL,
    rate        int,
    mpa_rate_id int REFERENCES mpa_rate (mpa_rate_id)
);

CREATE TABLE IF NOT EXISTS film_genre
(
    film_id  int REFERENCES films (film_id),
    genre_id int REFERENCES genre (genre_id),
    PRIMARY KEY (film_id, genre_id)
);

CREATE TABLE IF NOT EXISTS users
(
    user_id  int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email    varchar(30) NOT NULL,
    login    varchar(20) NOT NULL,
    name     varchar(30) NOT NULL,
    birthday date        NOT NULL
);

CREATE TABLE IF NOT EXISTS likes
(
    user_id int REFERENCES users (user_id),
    film_id int REFERENCES films (film_id),
    PRIMARY KEY (user_id, film_id)
);


CREATE TABLE IF NOT EXISTS friends
(
    user_id   int REFERENCES users (user_id),
    friend_id int REFERENCES users (user_id),
    PRIMARY KEY (user_id, friend_id)
);